/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/active-workout`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(nutrition)'}/create-recipe` | `/create-recipe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(nutrition)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(nutrition)'}/log` | `/log`; params?: Router.UnknownInputParams; } | { pathname: `${'/(nutrition)'}/nutrition-settings` | `/nutrition-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(nutrition)'}/recipes` | `/recipes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/progress` | `/progress`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/active-workout`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(nutrition)'}/create-recipe` | `/create-recipe`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(nutrition)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(nutrition)'}/log` | `/log`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(nutrition)'}/nutrition-settings` | `/nutrition-settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(nutrition)'}/recipes` | `/recipes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/progress` | `/progress`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/active-workout${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(nutrition)'}/create-recipe${`?${string}` | `#${string}` | ''}` | `/create-recipe${`?${string}` | `#${string}` | ''}` | `${'/(nutrition)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(nutrition)'}/log${`?${string}` | `#${string}` | ''}` | `/log${`?${string}` | `#${string}` | ''}` | `${'/(nutrition)'}/nutrition-settings${`?${string}` | `#${string}` | ''}` | `/nutrition-settings${`?${string}` | `#${string}` | ''}` | `${'/(nutrition)'}/recipes${`?${string}` | `#${string}` | ''}` | `/recipes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/library${`?${string}` | `#${string}` | ''}` | `/library${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/progress${`?${string}` | `#${string}` | ''}` | `/progress${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/active-workout`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(nutrition)'}/create-recipe` | `/create-recipe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(nutrition)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(nutrition)'}/log` | `/log`; params?: Router.UnknownInputParams; } | { pathname: `${'/(nutrition)'}/nutrition-settings` | `/nutrition-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(nutrition)'}/recipes` | `/recipes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/progress` | `/progress`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
